# Generated by Django 3.2.5 on 2022-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='cquery',
        ),
        migrations.AlterField(
            model_name='myskill',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
